// Generated by Wrangler on Tue Apr 09 2024 12:51:09 GMT+0100 (British Summer Time)
// by running `wrangler types --env-interface WranglerEnv wrangler.d.ts`

interface WranglerEnv {
	HELLO_WORKER: Fetcher;
	SUM_CONSUMER: Fetcher;
	SUM: Fetcher;
}
