// Generated by Wrangler on Tue Apr 09 2024 12:31:13 GMT+0100 (British Summer Time)
// by running `wrangler types --env-interface WranglerEnv wrangler.d.ts`

interface WranglerEnv {
	HELLO_WORKER: Fetcher;
}
